# Project configuration
sonar.projectKey=Maryamhammid_cohort-9-mern-8973-maryam
sonar.organization=maryamhammid
sonar.sources=backend/src,frontend/src
sonar.exclusions=**/node_modules/**,**/test/**,**/*.test.js,**/*.test.jsx,**/dist/**